### ISSUE TITLE
Blog Roll performance

### ISSUE THREAD

**Issue by DotNetWorker** [BlogEngine/BlogEngine.NET#100] opened 2016-09-05 14:46 UTC
There is an issue with performance and the blog roll, causes 60 seconds page load time for each page request. I assume there is a failure to cache correctly, removing the widget from the site makes site page load time go back to sub second response.

Confirmed by another user in this post:
https://blogengine.codeplex.com/discussions/655362

**Comment by rxtur** [comment] 2016-09-07 17:36
Do you have any broken URLs in the blogroll? I don't see this delay and adding blogroll to test site (http://zoo.azurewebsites.net) doesn't seem to have any impact on page time load. I'm closing it as I can't reproduce an issue, but if you can point me how to do it will re-open.

**Comment by DotNetWorker** [comment] 2016-09-07 20:56
I've updated to Standard theme IE fixed. FontAwesome added. 
commit 0e06817a902b418dba38104100af29a8a95dc5a0 
http://timwappat.info
And as soon as I put the blogroll on the page my inter page load time goes up to 6 seconds from sub seconds. 
I expect one of the feeds, as you say, was down causing time outs when I originally experienced this, which will be why it was up near 60 seconds then.

I agree that if the blogroll is fetching the syndication feeds from all the urls for each page request on my blog, this would be expected performance. However guess I expected the widget to be cached to protect the source blog feeds from my blog calling them too much each time a visitor requests a page and also to prevent the performance hit I am seeing between page loads. It would also prevent one of the blog feeds from taking my site down should the feed go down. 

Thus I would say this is still an issue, although would migrate to a feature request.
I guess it comes down to is there supposed to be any output cache of the widget or cache of the XML feeds? 

Love BlogEngine so this is intended to be constructive comment.

Tim

**Comment by sqc1999** [comment] 2016-09-08 14:04
@rxtur I agree with @DotNetWorker, it will be really annoying if any of the feeds can't be loaded quickly. In fact I've removed the blogroll widget from my blog just because of the problem. I think adding some form of caching is a good solution.

**Comment by scrummie02** [comment] 2016-10-13 12:26
Same issue here, I removed it.

**Closed** 2020-10-16 08:22 UTC
